### ISSUE TITLE
Generated files should have conventional file header

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffelevents-sdk-go#96]
### Description

The files we generate have a comment right after the copyright block:

    // THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED BY HAND.

This is fine, but the [`go generate` conventions](https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source) call for something else:

    // Code generated <optional text> DO NOT EDIT.

gopls and other tools detect this and are, for example, able to warn the user.

### Expected Behavior

I expect the SDK to follow established standard and conventions for Go code.

### The version/edition of the Eiffel Protocol used, if applicable

N/A

**Comment by JonasAlfredsson** [comment]
> To convey to humans and machine tools that code is generated, generated source should have a line that matches the following regular expression (in Go syntax):
> ```
> ^// Code generated .* DO NOT EDIT\.$
> ```
> This line must appear before the first non-comment, non-blank text in the file. 

To me it looks like you need a trailing period as well.

**Comment by magnusbaeck** [comment]
Correct, thanks. Description updated.
